"""add_website_audit_table

Revision ID: 3a384b37c187
Revises: c8dbd4c7a5eb
Create Date: 2026-06-24 15:02:30.842892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a384b37c187'
down_revision: Union[str, Sequence[str], None] = 'c8dbd4c7a5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('business_client_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('is_https', sa.Boolean(), nullable=True),
    sa.Column('redirected_url', sa.String(length=500), nullable=True),
    sa.Column('load_time_ms', sa.Float(), nullable=True),
    sa.Column('dom_content_loaded_ms', sa.Float(), nullable=True),
    sa.Column('first_paint_ms', sa.Float(), nullable=True),
    sa.Column('broken_links_count', sa.Integer(), nullable=True),
    sa.Column('broken_images_count', sa.Integer(), nullable=True),
    sa.Column('broken_links_detail', sa.JSON(), nullable=True),
    sa.Column('seo_title', sa.String(length=500), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_keywords', sa.Text(), nullable=True),
    sa.Column('has_h1', sa.Boolean(), nullable=True),
    sa.Column('has_canonical', sa.Boolean(), nullable=True),
    sa.Column('og_title', sa.String(length=500), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('raw_seo_tags', sa.JSON(), nullable=True),
    sa.Column('missing_alt_images_count', sa.Integer(), nullable=True),
    sa.Column('missing_label_inputs_count', sa.Integer(), nullable=True),
    sa.Column('has_lang_attr', sa.Boolean(), nullable=True),
    sa.Column('accessibility_issues', sa.JSON(), nullable=True),
    sa.Column('console_errors_count', sa.Integer(), nullable=True),
    sa.Column('console_warnings_count', sa.Integer(), nullable=True),
    sa.Column('console_logs', sa.JSON(), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_client_id'], ['business_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_audits_business_client_id'), 'website_audits', ['business_client_id'], unique=False)
    op.create_index(op.f('ix_website_audits_uuid'), 'website_audits', ['uuid'], unique=True)
    op.alter_column('business_clients', 'is_approached',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('business_clients', 'scrape_source',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('business_clients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('business_clients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('uuid'), table_name='business_clients')
    op.create_index(op.f('ix_business_clients_uuid'), 'business_clients', ['uuid'], unique=True)
    op.alter_column('scrape_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_index(op.f('uuid'), table_name='scrape_sessions')
    op.create_index(op.f('ix_scrape_sessions_uuid'), 'scrape_sessions', ['uuid'], unique=True)
    op.alter_column('scraped_raw_data', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index(op.f('uuid'), table_name='scraped_raw_data')
    op.create_index(op.f('ix_scraped_raw_data_id'), 'scraped_raw_data', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_raw_data_uuid'), 'scraped_raw_data', ['uuid'], unique=True)
    op.alter_column('scraper_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraper_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scraper_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.drop_index(op.f('ix_scraped_raw_data_uuid'), table_name='scraped_raw_data')
    op.drop_index(op.f('ix_scraped_raw_data_id'), table_name='scraped_raw_data')
    op.create_index(op.f('uuid'), 'scraped_raw_data', ['uuid'], unique=True)
    op.alter_column('scraped_raw_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.drop_index(op.f('ix_scrape_sessions_uuid'), table_name='scrape_sessions')
    op.create_index(op.f('uuid'), 'scrape_sessions', ['uuid'], unique=True)
    op.alter_column('scrape_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               nullable=True)
    op.drop_index(op.f('ix_business_clients_uuid'), table_name='business_clients')
    op.create_index(op.f('uuid'), 'business_clients', ['uuid'], unique=True)
    op.alter_column('business_clients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('business_clients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               nullable=True)
    op.alter_column('business_clients', 'scrape_source',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('business_clients', 'is_approached',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_index(op.f('ix_website_audits_uuid'), table_name='website_audits')
    op.drop_index(op.f('ix_website_audits_business_client_id'), table_name='website_audits')
    op.drop_table('website_audits')
    # ### end Alembic commands ###
