"""Add ProfileSetting model

Revision ID: a1b8f52c3c44
Revises: e1f2a3b4c5d6
Create Date: 2026-07-07 12:55:12.624173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a1b8f52c3c44'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_connections_per_day', sa.Integer(), nullable=True),
    sa.Column('max_messages_per_day', sa.Integer(), nullable=True),
    sa.Column('allowed_processes', sa.Text(), nullable=True),
    sa.Column('profile_type', sa.String(length=50), nullable=True),
    sa.Column('session_state', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_settings_id'), 'profile_settings', ['id'], unique=False)
    op.create_index(op.f('ix_profile_settings_name'), 'profile_settings', ['name'], unique=True)
    op.alter_column('business_clients', 'is_linkedin_searched',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('business_clients', 'linkedin_search_status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('business_clients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('business_clients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('lead_scores', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('linkedin_contacts', 'match_confidence',
               existing_type=mysql.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('linkedin_contacts', 'connection_sent',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('linkedin_contacts', 'is_connected',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('linkedin_contacts', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('uuid'), table_name='linkedin_contacts')
    op.alter_column('sales_pitches', 'pitch_channel',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sales_pitches', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sales_pitches', 'delivery_status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sales_pitches', 'delivery_attempts',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales_pitches', 'reply_received',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('fk_sales_pitches_linkedin_contact_id'), 'sales_pitches', type_='foreignkey')
    op.create_foreign_key(None, 'sales_pitches', 'linkedin_contacts', ['linkedin_contact_id'], ['id'])
    op.alter_column('scrape_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('scraped_raw_data', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraper_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('website_audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('scraper_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scrape_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.drop_constraint(None, 'sales_pitches', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sales_pitches_linkedin_contact_id'), 'sales_pitches', 'linkedin_contacts', ['linkedin_contact_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sales_pitches', 'reply_received',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sales_pitches', 'delivery_attempts',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sales_pitches', 'delivery_status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'pending'"),
               existing_nullable=True)
    op.alter_column('sales_pitches', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('sales_pitches', 'pitch_channel',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'generic'"),
               existing_nullable=True)
    op.create_index(op.f('uuid'), 'linkedin_contacts', ['uuid'], unique=True)
    op.alter_column('linkedin_contacts', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('linkedin_contacts', 'is_connected',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('linkedin_contacts', 'connection_sent',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('linkedin_contacts', 'match_confidence',
               existing_type=mysql.VARCHAR(length=10),
               server_default=sa.text("'medium'"),
               existing_nullable=True)
    op.alter_column('lead_scores', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('business_clients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('business_clients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('business_clients', 'linkedin_search_status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'pending'"),
               existing_nullable=True)
    op.alter_column('business_clients', 'is_linkedin_searched',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_profile_settings_name'), table_name='profile_settings')
    op.drop_index(op.f('ix_profile_settings_id'), table_name='profile_settings')
    op.drop_table('profile_settings')
    # ### end Alembic commands ###
