"""add_lead_scores_sales_pitches_is_scored

Revision ID: aff43a14e300
Revises: cc45e8bf3bbb
Create Date: 2026-06-26 12:17:09.554200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aff43a14e300'
down_revision: Union[str, Sequence[str], None] = 'cc45e8bf3bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_clients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('business_clients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scrape_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('scraped_raw_data', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraper_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.add_column('website_audits', sa.Column('is_scored', sa.Boolean(), nullable=False))
    op.alter_column('website_audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.drop_column('website_audits', 'is_scored')
    op.alter_column('scraper_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scrape_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('business_clients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('business_clients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    # ### end Alembic commands ###
