"""create_lead_scores_and_sales_pitches_tables

Revision ID: e53ae437ef86
Revises: aff43a14e300
Create Date: 2026-06-26 12:18:28.683660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e53ae437ef86'
down_revision: Union[str, Sequence[str], None] = 'aff43a14e300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('business_client_id', sa.Integer(), nullable=False),
    sa.Column('website_audit_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('issues_found', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_client_id'], ['business_clients.id'], ),
    sa.ForeignKeyConstraint(['website_audit_id'], ['website_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_scores_business_client_id'), 'lead_scores', ['business_client_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_uuid'), 'lead_scores', ['uuid'], unique=True)
    op.create_index(op.f('ix_lead_scores_website_audit_id'), 'lead_scores', ['website_audit_id'], unique=False)
    op.create_table('sales_pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('business_client_id', sa.Integer(), nullable=False),
    sa.Column('lead_score_id', sa.Integer(), nullable=False),
    sa.Column('pitch_subject', sa.Text(), nullable=True),
    sa.Column('pitch_hook', sa.Text(), nullable=True),
    sa.Column('pitch_body', sa.Text(), nullable=True),
    sa.Column('key_pain_points', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_client_id'], ['business_clients.id'], ),
    sa.ForeignKeyConstraint(['lead_score_id'], ['lead_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_pitches_business_client_id'), 'sales_pitches', ['business_client_id'], unique=False)
    op.create_index(op.f('ix_sales_pitches_lead_score_id'), 'sales_pitches', ['lead_score_id'], unique=False)
    op.create_index(op.f('ix_sales_pitches_uuid'), 'sales_pitches', ['uuid'], unique=True)
    op.alter_column('business_clients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('business_clients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scrape_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('scraped_raw_data', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scraper_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('website_audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('scraper_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scraped_raw_data', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('scrape_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('business_clients', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('business_clients', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_sales_pitches_uuid'), table_name='sales_pitches')
    op.drop_index(op.f('ix_sales_pitches_lead_score_id'), table_name='sales_pitches')
    op.drop_index(op.f('ix_sales_pitches_business_client_id'), table_name='sales_pitches')
    op.drop_table('sales_pitches')
    op.drop_index(op.f('ix_lead_scores_website_audit_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_uuid'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_business_client_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    # ### end Alembic commands ###
