import uuid
from sqlalchemy import Column, String, DateTime, Integer, Boolean, ForeignKey, Text, func
from app.config.database import Base


class ClientChatMessage(Base):
    __tablename__ = "client_chat_messages"

    id = Column(Integer, primary_key=True)
    uuid = Column(
        String(36),
        nullable=False,
        unique=True,
        index=True,
        default=lambda: str(uuid.uuid4()),
    )

    # Account profile context
    profile_id = Column(Integer, ForeignKey("profile_settings.id"), nullable=True, index=True)

    # Associated entities
    sales_pitch_id = Column(Integer, ForeignKey("sales_pitches.id"), nullable=True, index=True)
    linkedin_contact_id = Column(Integer, ForeignKey("linkedin_contacts.id"), nullable=True, index=True)
    linkedin_search_contact_id = Column(Integer, ForeignKey("linkedin_search_contacts.id"), nullable=True, index=True)

    # Message details
    sender = Column(String(50), nullable=False)   # "You" or "Them"
    message_body = Column(Text, nullable=False)
    is_self = Column(Boolean, default=False, nullable=False)

    # LLM & Webhook fields
    suggested_reply = Column(Text, nullable=True)     # Recommended response generated by LLM
    telegram_chat_id = Column(String(100), nullable=True, index=True)  # Captured from Telegram webhook data[0].chat_id

    # Workflow status: "received", "pending_approval", "approved", "rejected", "sent", "failed"
    status = Column(String(50), nullable=True, default="received", index=True)
    sent_reply_text = Column(Text, nullable=True)     # Actual text sent back to client

    conversation_active = Column(Boolean, default=False, nullable=False)

    created_at = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=True,
    )
